### ISSUE TITLE
Feature: Filter by glob or extension in cli

### ISSUE THREAD

**Issue by Ciantic** [mikeal/watch#106]
I'm sick and tired of these bad less watchers. Those has lead me to here. I still need a way to define file filter to use this instead.

Example:

`watch "lessc style.less style.css" --globFilter **.less`

`globFilter` would make my life so much easier. Thanks.

**Comment by Ciantic** [comment]
Closing this, this is duplicate. Apologies.

**Comment by levithomason** [comment]
Honest question, are you sick and tired enough to help me a better one?  I'm a recent new contributor here and hope to make a better watch package.  If you'd like to see this one become that package, it would be great to get some PR reviews and input on the ideas being put forward.  Thanks much!

**Comment by Ciantic** [comment]
@levithomason I'm sick and tired of *LESS* (the css preprocessor) watchers — not this one! Though unfortunately I found what I needed already: https://github.com/queckezz/watch-run

**Comment by levithomason** [comment]
Thanks for the clarification, I've heard some good things about watch-run.  Will check it out.
