### ISSUE TITLE
When using the cli --interval with multiple dirs the interval is incrementaly multiplyed by 1000

### ISSUE THREAD

**Issue by fppgodinho** [mikeal/watch#125]
Everytime the watch.watchTree is invoked, for example for each directory, the watchTreeOpts.interval get's multiplied by 1000.

Works fine with a single dir where it converts the target seconds to milliseconds  but after the first will become 2000 seconds etc...

**Comment by levithomason** [comment]
Fixed in https://github.com/mikeal/watch/pull/126
