### ISSUE TITLE
Events always fire 2 times

### ISSUE THREAD

**Issue by tanertopal** [mikeal/watch#14]
When i use the Example Code:

watch.createMonitor('/home/mikeal', function (monitor) {
    monitor.files['/home/mikeal/.zshrc'] // Stat object for my zshrc.
    monitor.on("created", function (f, stat) {
      // Handle file changes
    })
    monitor.on("changed", function (f, curr, prev) {
      // Handle new files
    })
    monitor.on("removed", function (f, stat) {
      // Handle removed files
    })
  }  

The Create Events fire 2 times. Any reason why this could happen? I looked into the Code but have no idea.

**Comment by fontanon** [comment]
thanks @ignatiusd your work-around worked for me too!

**Comment by levithomason** [comment]
Looks like the work around is acceptable, please open a new issue if you anyone is still experiencing problems.
