### ISSUE TITLE
Upgrade merge to version 1.2.1 or later.

### ISSUE THREAD

**Issue by forgo** [mikeal/watch#144]
It appears you have a downstream dependency on a vulnerable package `merge`. Please refer to my detailed issue on a a more upstream project. The issue was flagged automatically on my GitHub repository as a **"high severity"** alert.

https://github.com/fuse-box/fuse-box/issues/1427

**Comment by forgo** [comment]
Closing this as it is likely only a versioning issue with the fuse-box version I am referencing.

**Comment by forgo** [comment]
Re-opening, as I believe this could be fixed by upgrading your dependency `exec-sh` from  0.2.0 to 0.3.2. That latest version seems not to depend on `merge` at all now.

**Comment by stevenzeck** [comment]
@forgo try deleting your `package-lock.json` and `node_modules` folder, then run npm install again.

**Comment by jsebrech** [comment]
I can confirm that deleting package-lock.json and node_modules and then running npm install works to upgrade merge to 1.2.1.

**Comment by Simkhotech** [comment]
> I can confirm that deleting package.json and node_modules and then running npm install works to upgrade merge to 1.2.1.

**package-lock.json**... not **package.json**
@jsebrech  Is it typo?

**Comment by jsebrech** [comment]
Yes, I fixed my comment.
