### ISSUE TITLE
Not Found @cnakazawa/watch

### ISSUE THREAD

**Issue by tgl-lampd** [mikeal/watch#160]
I have an error when I run "npm i"

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cnakazawa%2fwatch - Not found
npm ERR! 404 
npm ERR! 404  '@cnakazawa/watch@^1.0.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'sane'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Jonasb8** [comment]
same issue here
I have the feeling that the repo is now private

**Comment by divyam-rai** [comment]
Same issue on my end as well 😢
Does seem that the repository and package have gone private.

**Comment by priusGit** [comment]
NPM has incident atm: https://status.npmjs.org/incidents/drj38qn6qm59

**Comment by tgl-lampd** [comment]
> NPM has incident atm: https://status.npmjs.org/incidents/drj38qn6qm59

Thank you, I'm going to close this issue
