### ISSUE TITLE
No directory delete detection

### ISSUE THREAD

**Issue by outaTiME** [mikeal/watch#17]
Hi again, 

no directory delete detection ... any ideas ?? other things works fine ... 

there ... the code example ... the same in README file ...

```javascript
watch.watchTree(target, function (f, curr, prev) {
  if (typeof f == "object" && prev === null && curr === null) {
    // Finished walking the tree
  } else if (prev === null) {
    console.log('New file: %s', f);
    // f is a new file
  } else if (curr.nlink === 0) {
    // f was removed
    console.log('File removed: %s', f);
  } else {
    // f was changed
    console.log('File changed: %s', f);
  }
});
```

when i delete directory from 'target' no file removed thrown :(

thks !

**Comment by levithomason** [comment]
This seems to be working in the latest version.  Please open a new issue if you are still experiencing issues.
