### ISSUE TITLE
Is watch supposed to be so slow?

### ISSUE THREAD

**Issue by philipwalton** [mikeal/watch#46]
I'm using the example code from the README and watching a directory with only three files in it. When I make a change to one of the files it's taking anywhere between 1 and 4 seconds to report. When I simply use `fs.watch` the change is reported almost immediately.

Is this expected? If not, do you have any idea what might be causing the slowness?

**Comment by sandric** [comment]
well, I'm on archlinux with latest 3.18.6 kernel and it takes me this long too..

**Comment by marlun** [comment]
I'm on OS X too but is there no solution?

**Comment by jnak** [comment]
+1

**Comment by TYRONEMICHAEL** [comment]
+1

**Comment by TYRONEMICHAEL** [comment]
Ok so I think I found the issue. Comparing `wr` vs `watch`, the issue is the difference between fs.watch & and fs.watchFile. To quote the Node docs:

> fs.watch is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

Also this link provides good insight to the difference between the two methods [link] (http://tech.nitoyon.com/en/blog/2013/10/02/node-watch-impl/)

**Comment by deathmood** [comment]
It is not only on mac - I'm on windows -- and it takes about 3-4 seconds to _notice_ the change

**Comment by kafoso** [comment]
@deathmood Same here. It is extremely cumbersome and is pretty CPU intensive.

**Comment by levithomason** [comment]
I recently merged an update that sped things up quite a bit.  Can you post your version numbers?
