### ISSUE TITLE
watch multiple directories from CLI?

### ISSUE THREAD

**Issue by tejacques** [mikeal/watch#73]
It doesn't look like there's currently a way to do this (from the CLI). It would be nice if the watch CLI could take multiple directories to watch:

Something like this:
watch \<command\> [...directory] [--wait=\<seconds\>] [--ignoreDotFiles] [--ignoreUnreadable]

Ex:
watch "echo file changed" dir1/ dir2/

**Comment by tejacques** [comment]
I made a pretty simple change to cli.js in a fork (referenced above). If this is a feature you think would be useful to others and you'd like a PR let me know.

**Comment by finnp** [comment]
Seems handy :+1:  Could you PR this and change the readme.md as well?
