### ISSUE TITLE
How do I "unwatch" or `npm stop`?

### ISSUE THREAD

**Issue by lfilho** [mikeal/watch#79]
First of all, thanks for you work!

I'm trying to use `watch` cli as part of my npm scripts, like so:

```
"scripts": { 
    "start": "node index",
    "js:watch": "watch 'npm start' lib/"
}
```
But then everytime a file changes, it gives the `EADDRINUSE`, as the server (`node index`) is already started... How can I accomplish this? What should I put in `npm stop` script or what should I pass to `watch`?

Thank you!

**Comment by evilsoft** [comment]
Typically the watch is used to trigger a step in the build process, not for controlling your node app.
So if you are using this to restart your server, you may wanna utilize `[npm restart](https://docs.npmjs.com/cli/restart)`.
But there are other tools that may be better suited to control your app at this level, so you do not have to manage the process. One example is [nodemon](https://github.com/remy/nodemon).

TBH, I have only used watch CLI for watching say my Sass or Less folders and rebuilding my assets. Not so much Sass anymore as it's watch arg has improved...But still use it for Less.

**Comment by evilsoft** [comment]
Granted this is for a build system, but this is one of the use case I use `watch` for: [simply-evil-js package.json](https://github.com/evilsoft/simply-evil-js/blob/master/package.json#L9)

**Comment by grantwparks** [comment]
Is it possible to stop, though?  That's the question; it's a legitimate need to be able to stop the current watch.
