### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by levithomason** [mikeal/watch#96]
There are 6 PRs open going back to Oct of 2015.  I've also been trying to get some movement on #84 since Mar 8.  Please respond.  This is a great package holding a superb npm name, it would be a bummer to see it go stale.

Also, (again) willing to help!

**Comment by mikeal** [comment]
Anyone who lands a commit will get write access.

**Comment by levithomason** [comment]
Sounds good, how do we go about landing a commit with no access?

**Comment by levithomason** [comment]
I've opened #97 which updates the seemingly dead #84.  It has been squashed and all comments addressed.  LMK if this works.
